
const DashboardConstants = {
    RECIEVE_RAW_WEATHER: 'RECIEVE_RAW_WEATHER',
    RECIEVE_RAW_POLLEN: 'RECIEVE_RAW_POLLEN',
    RECIEVE_RAW_CALENDAR_EVENTS: 'RECIEVE_RAW_CALENDAR_EVENTS',
    RECIEVE_RAW_CALENDAR_LIST: 'RECIEVE_RAW_CALENDAR_LIST',
    RECIEVE_CALENDAR_AUTH_CHECK_RESULT: 'RECIEVE_CALENDAR_AUTH_CHECK_RESULT',
    RECIEVE_RAW_NEWS_EVENTS: 'RECIEVE_RAW_NEWS_EVENTS',
    SHOW_SETTINGS: 'SHOW_SETTINGS',
    RECIEVE_SETTINGS: 'RECIEVE_SETTINGS',
    SHOW_HOME: 'SHOW_HOME',
    RECIEVE_GEOPOINT: 'RECIEVE_GEOPOINT',
    RECIEVE_LOCATION_INFO: 'RECIEVE_LOCATION_INFO',
    RECIEVE_QUAKE_INFO: 'RECIEVE_QUAKE_INFO'
};

export default DashboardConstants;