version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.7.1-stretch-browsers
    steps:
      - checkout

      # Execute the build process
      - run:
          name: Fetch and Install packages
          command: yarn
      - run: 
          name: Create optimized production build
          command: yarn build

      # Execute the packaging process
      - run: 
          name: Emit build number
          command: echo "{\"version\":$CIRCLE_BUILD_NUM}" >> build/build.json
      - run: 
          name: Create the zip file
          command: cd build; zip -r9 /tmp/dashboard-ui.zip .

      # Tuck away our artifacts
      - store_artifacts:
          path: /tmp/dashboard-ui.zip