version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.7.1-stretch-browsers
    steps:
      - checkout

      # Execute the build process
      - run: yarn
      - run: yarn build

      # Build the dashboard zip file
      - run: echo "{\"version\":$CIRCLE_BUILD_NUM}" >> build/build.json
      - run: cd build; zip -r9 /tmp/dashboard-ui.zip .

      # Tuck away our artifacts
      - store_artifacts:
          path: /tmp/dashboard-ui.zip