version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.7.1-stretch-browsers
    steps:
      - checkout

      # Restore our dependency cache
      - restore_cache:
          keys: 
            - node-cache-{{ checksum "package.json" }}
            - node_cache- 

      # Execute the build process
      - run:
          name: Fetch and Install packages
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: node-cache-{{ checksum "package.json" }}

      - run: 
          name: Create optimized production build
          command: yarn build

      # Execute the packaging process
      - run: 
          name: Emit build number
          command: echo "{\"version\":$CIRCLE_BUILD_NUM}" >> build/build.json
      - run: 
          name: Create the zip file
          command: cd build; zip -r9 /tmp/dashboard-ui.zip .

      # Tuck away our artifacts
      - store_artifacts:
          path: /tmp/dashboard-ui.zip

      # Persist the built (unzipped) app to the workspace
      - persist_to_workspace:
          root: .
          paths:
            - build

      # Persist the zip artifact to the workspace
      - persist_to_workspace:
          root: /tmp
          paths:
            - dashboard-ui.zip

  deploy:
    docker:
      - image: circleci/python:3.4-jessie-browsers
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Set path
          command: export PATH=~/bin:$PATH

      # Get our dependencies:
      - run:
          name: Install AWS tools
          command: |            
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            ./awscli-bundle/install -b ~/bin/aws

      # Prep Cloudflare for deployment
      - run: "curl -X PATCH \"https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/settings/development_mode\" -H \"X-Auth-Email: $CLOUDFLARE_EMAIL\" -H \"X-Auth-Key: $CLOUDFLARE_API_KEY\" -H \"Content-Type: application/json\" --data '{\"value\":\"on\"}'"

      # Push to s3.  This expects the environment variables
      # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to be set
      # See http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment 
      # for more information
      - run: /home/circleci/bin/aws s3 sync /tmp/workspace/build s3://$S3_DEPLOY_BUCKET --quiet

  release:
    docker:
      - image: circleci/golang:1.9.4
    steps:
      - attach_workspace:
          at: /tmp/workspace

      # Get our release maker
      - run: go get github.com/tcnksm/ghr

      # Push our release to github:
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v1.0.$CIRCLE_BUILD_NUM /tmp/workspace/dashboard-ui.zip || true

workflows:
  version: 2

  # Build and deploy workflow
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - release:
          requires:
            - build